select * from EMPLOYEES;
select * from DEPARTMENTS;

--department_id is same parameter

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e join DEPARTMENTS d
on e.DEPARTMENT_ID=d.DEPARTMENT_ID;

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e left join DEPARTMENTS d
on e.DEPARTMENT_ID=d.DEPARTMENT_ID;

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e right join DEPARTMENTS d
on e.DEPARTMENT_ID=d.DEPARTMENT_ID;

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e full join DEPARTMENTS d
on e.DEPARTMENT_ID=d.DEPARTMENT_ID;

